jobs:
  deploy:
    name: Deploy chat-application Fargate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1 # faz checkout do meu repositório ref https://github.com/actions/checkout
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: chat-application
        IMAGE_TAG: ${GITHUB_SHA_SHORT} #pegando a short hash do commit ref: https://gist.github.com/lwiedenhoeft/c2bf48e128cbc1213bc5d3412212add38a4d
      
        run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Render Amazon ECS task definition
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: chat-application
        IMAGE_TAG: ${env.GITHUB_SHA_SHORT}
      with:
        task-definition: task-definition.json
        container-name: chat-application
        image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-web-container.outputs.task-definition }}
        service: chat-application
        cluster: chat-application

on:
  push:
    branches: [ master ]